### ISSUE TITLE
Support 6to5

### ISSUE THREAD

**Issue by matthewp** [bitovi/transpile#15]
Now that SystemJS supports 6to5 it would be nice to have this support in transpile.  `System.transpiler` is set to either `traceur` (default) or `6to5`. This could be passed in via the `options` object and used to determine which compiler to use.

**Comment by justinbmeyer** [comment]
Part of me wonders if `options` should be an object that looks like a "System"

**Comment by matthewp** [comment]
Why? This project is not related to SystemJS. It can be used regardless of what module loader you choose. I wouldn't want to tie their APIs together like that.

**Comment by justinbmeyer** [comment]
Because it's an API that we can base something around that people might understand.

Say people wanted to provided a mapping, maybe it should be `options.map`.  Or some other {meta} thing that we could use to convert globals to AMD / CJS / etc (instead of System.define), maybe it should be `options.meta.global`.

We are already basing the API off of a Loader load object.  I'm not suggesting making it dependent on SystemJS, I'm suggesting making their APIs parallel for conformity sake.

**Comment by matthewp** [comment]
In that case I should update the option to be `transpiler` which felt wrong for this project.

**Comment by matthewp** [comment]
Let me update this to be called `transpiler` before we merge.
